#!/bin/bash
# Send brief to Slack via webhook
#
# Usage: ./send_slack.sh <person_name> <brief_text_file> <webhook_url>

set -e

PERSON_NAME="$1"
BRIEF_FILE="$2"
WEBHOOK_URL="$3"

if [ -z "$WEBHOOK_URL" ]; then
  echo "Error: Webhook URL required"
  exit 1
fi

if [ ! -f "$BRIEF_FILE" ]; then
  echo "Error: Brief file not found: $BRIEF_FILE"
  exit 1
fi

# Format for Slack (convert markdown to mrkdwn)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BRIEF_TEXT=$("$SCRIPT_DIR/format_for_slack.sh" "$BRIEF_FILE")

# Create simple Slack message payload (blocks have 3000 char limit, plain text has 40K limit)
jq -n \
  --arg name "$PERSON_NAME" \
  --arg text "$BRIEF_TEXT" \
  '{
    "text": ("📅 *Meeting Brief: " + $name + "*\n\n" + $text + "\n\n_Generated by meeting-brief skill_")
  }' > /tmp/slack_payload.json

# Send to Slack
curl -X POST \
  -H 'Content-Type: application/json' \
  -d @/tmp/slack_payload.json \
  "$WEBHOOK_URL"

rm -f /tmp/slack_payload.json

echo "✓ Slack notification sent for ${PERSON_NAME}"
