-- ============================================================================
-- V7.1 Schema Validation Migration
-- ============================================================================
-- Adds validation functions and triggers for V7 lessons to ensure JSON conformity
-- Created: 2024-12-22

-- ============================================================================
-- VALIDATION FUNCTION FOR V7.1 SCHEMA
-- ============================================================================

CREATE OR REPLACE FUNCTION validate_v7_lesson_schema(content JSONB)
RETURNS BOOLEAN AS $$
DECLARE
  version TEXT;
  acts JSONB;
  act JSONB;
  act_type TEXT;
  valid_types TEXT[] := ARRAY['dramatic', 'narrative', 'interaction', 'playground', 'revelation', 'gamification', 'quiz', 'comparison', 'cta', 'result'];
BEGIN
  -- Check version (accept both 7.1 and legacy 2.x versions for backward compatibility)
  version := content->>'version';
  IF version IS NULL THEN
    RAISE NOTICE 'V7 Validation: No version field, assuming legacy format';
    RETURN TRUE; -- Allow legacy content without version
  END IF;

  -- Get acts from cinematic_flow
  acts := content->'cinematic_flow'->'acts';
  IF acts IS NULL OR jsonb_array_length(acts) = 0 THEN
    RAISE NOTICE 'V7 Validation: No acts found in cinematic_flow';
    -- For version 7.1, acts are required
    IF version = '7.1' THEN
      RETURN FALSE;
    END IF;
    RETURN TRUE;
  END IF;

  -- Validate each act
  FOR act IN SELECT * FROM jsonb_array_elements(acts)
  LOOP
    -- Check required fields
    IF act->>'id' IS NULL THEN
      RAISE NOTICE 'V7 Validation: Act missing id';
      RETURN FALSE;
    END IF;

    IF act->>'type' IS NULL THEN
      RAISE NOTICE 'V7 Validation: Act % missing type', act->>'id';
      RETURN FALSE;
    END IF;

    -- Validate act type
    act_type := act->>'type';
    IF NOT (act_type = ANY(valid_types)) THEN
      RAISE NOTICE 'V7 Validation: Invalid act type % for act %', act_type, act->>'id';
      RETURN FALSE;
    END IF;

    -- For V7.1, interactive acts should have pauseKeyword (warning, not error)
    IF version = '7.1' AND (act_type = 'interaction' OR act_type = 'playground' OR act_type = 'quiz') THEN
      IF act->>'pauseKeyword' IS NULL AND act->'pauseKeywords' IS NULL THEN
        RAISE NOTICE 'V7 Validation Warning: Interactive act % should have pauseKeyword for word-based sync', act->>'id';
        -- Allow it, but warn (pauseKeyword can be auto-generated by frontend)
      END IF;
    END IF;

    -- Validate narration exists (warning for interactive phases)
    IF act->>'narration' IS NULL OR length(act->>'narration') = 0 THEN
      -- Check legacy location
      IF act->'content'->'audio'->>'narration' IS NULL OR length(act->'content'->'audio'->>'narration') = 0 THEN
        RAISE NOTICE 'V7 Validation Warning: Act % has no narration', act->>'id';
        -- Not an error, some acts may not have narration
      END IF;
    END IF;
  END LOOP;

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- TRIGGER FUNCTION TO VALIDATE ON INSERT/UPDATE
-- ============================================================================

CREATE OR REPLACE FUNCTION validate_v7_lesson_on_save()
RETURNS TRIGGER AS $$
BEGIN
  -- Only validate V7 lessons
  IF NEW.model = 'v7' OR NEW.lesson_type = 'v7-cinematic' THEN
    IF NOT validate_v7_lesson_schema(NEW.content) THEN
      RAISE EXCEPTION 'V7 lesson content does not conform to V7.1 schema. Check cinematic_flow.acts structure.';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- CREATE TRIGGER (if not exists pattern)
-- ============================================================================

DO $$
BEGIN
  -- Drop existing trigger if exists
  DROP TRIGGER IF EXISTS validate_v7_lesson_trigger ON public.lessons;

  -- Create new trigger
  CREATE TRIGGER validate_v7_lesson_trigger
    BEFORE INSERT OR UPDATE ON public.lessons
    FOR EACH ROW
    EXECUTE FUNCTION validate_v7_lesson_on_save();

  RAISE NOTICE 'V7 validation trigger created on lessons table';
EXCEPTION
  WHEN undefined_table THEN
    RAISE NOTICE 'lessons table does not exist, skipping trigger creation';
END;
$$;

-- ============================================================================
-- HELPER FUNCTION: Extract pauseKeywords from all acts
-- ============================================================================

CREATE OR REPLACE FUNCTION get_v7_pause_keywords(content JSONB)
RETURNS TEXT[] AS $$
DECLARE
  acts JSONB;
  act JSONB;
  keywords TEXT[] := ARRAY[]::TEXT[];
  kw TEXT;
BEGIN
  acts := content->'cinematic_flow'->'acts';
  IF acts IS NULL THEN
    RETURN keywords;
  END IF;

  FOR act IN SELECT * FROM jsonb_array_elements(acts)
  LOOP
    -- Get pauseKeyword
    kw := act->>'pauseKeyword';
    IF kw IS NOT NULL THEN
      keywords := array_append(keywords, kw);
    END IF;

    -- Get pauseKeywords array
    IF act->'pauseKeywords' IS NOT NULL THEN
      FOR kw IN SELECT jsonb_array_elements_text(act->'pauseKeywords')
      LOOP
        IF kw IS NOT NULL AND NOT (kw = ANY(keywords)) THEN
          keywords := array_append(keywords, kw);
        END IF;
      END LOOP;
    END IF;
  END LOOP;

  RETURN keywords;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- HELPER FUNCTION: Get act by type
-- ============================================================================

CREATE OR REPLACE FUNCTION get_v7_acts_by_type(content JSONB, act_type TEXT)
RETURNS JSONB AS $$
DECLARE
  acts JSONB;
  matching_acts JSONB := '[]'::JSONB;
  act JSONB;
BEGIN
  acts := content->'cinematic_flow'->'acts';
  IF acts IS NULL THEN
    RETURN matching_acts;
  END IF;

  FOR act IN SELECT * FROM jsonb_array_elements(acts)
  LOOP
    IF act->>'type' = act_type THEN
      matching_acts := matching_acts || jsonb_build_array(act);
    END IF;
  END LOOP;

  RETURN matching_acts;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- UPDATE COMMENTS
-- ============================================================================

COMMENT ON FUNCTION validate_v7_lesson_schema IS 'Validates V7.1 cinematic lesson JSON schema';
COMMENT ON FUNCTION validate_v7_lesson_on_save IS 'Trigger function to validate V7 lessons before save';
COMMENT ON FUNCTION get_v7_pause_keywords IS 'Extracts all pauseKeywords from V7 lesson acts';
COMMENT ON FUNCTION get_v7_acts_by_type IS 'Returns all acts of a specific type from V7 lesson';

-- ============================================================================
-- UPDATE v7_lessons TABLE COMMENT IF EXISTS
-- ============================================================================

DO $$
BEGIN
  EXECUTE 'COMMENT ON COLUMN public.v7_lessons.data IS ''V7.1 Cinematic Lesson JSON. Schema: version 7.1, cinematic_flow.acts with pauseKeyword support''';
EXCEPTION
  WHEN undefined_table THEN
    RAISE NOTICE 'v7_lessons table does not exist';
  WHEN undefined_column THEN
    RAISE NOTICE 'v7_lessons.data column does not exist';
END;
$$;

DO $$
BEGIN
  EXECUTE 'COMMENT ON COLUMN public.lessons.content IS ''Lesson content JSON. For V7: version 7.1, cinematic_flow.acts with word-based pauseKeyword sync''';
EXCEPTION
  WHEN undefined_table THEN
    RAISE NOTICE 'lessons table does not exist';
  WHEN undefined_column THEN
    RAISE NOTICE 'lessons.content column does not exist';
END;
$$;
